user_service:
    resource:
        path: ../src/UserService/Controller/
        namespace: Gateway\UserService\Controller
    type: attribute
    prefix: '/api'

api_login_check:
    path: /api/login
